# Generated by Django 5.0.1 on 2025-06-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprovado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escola', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=100)),
                ('nascimento', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='media/')),
                ('aprovados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aprovado')),
            ],
        ),
    ]
