# Generated by Django 5.0.1 on 2024-03-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_cadastro_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='nome',
        ),
    ]
