# Generated by Django 5.0.1 on 2024-03-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_cadastro_cpf_remove_cadastro_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
